name: Go

on:
  push:
    branches: [ "main" ]
    tags-ignore:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go mod tidy

    - name: Build
      run: |
        GOOS=linux GOARCH=amd64 go build -o dist/personal-finance-tracker-linux cmd/main.go
        GOOS=darwin GOARCH=amd64 go build -o dist/personal-finance-tracker-mac cmd/main.go
        GOOS=windows GOARCH=amd64 go build -o dist/personal-finance-tracker.exe cmd/main.go

    - name: Test
      run: go test -v ./...
